# Generated by Django 4.2.4 on 2024-02-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('ln', models.CharField(default='null', max_length=255, null=True, verbose_name='Отчество')),
                ('fn', models.CharField(default='null', max_length=255, null=True, verbose_name='Фамилия')),
                ('gen', models.CharField(default='f', max_length=255, null=True, verbose_name='Гендер')),
                ('age', models.IntegerField(default=0, null=True, verbose_name='Возраст')),
                ('dob', models.DateField(default='29.11.2023', null=True, verbose_name='Дата Рождения')),
                ('doby', models.CharField(default='null', max_length=255, null=True, verbose_name='Год рождения')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email_0')),
                ('email_1', models.EmailField(default='null', max_length=254, null=True, verbose_name='email_1')),
                ('email_2', models.EmailField(default='null', max_length=254, null=True, verbose_name='email_2')),
                ('phone', models.CharField(null=True, verbose_name='phone')),
                ('phone_3', models.CharField(default='null', max_length=255, null=True, verbose_name='phone_3')),
                ('phone_4', models.CharField(default='null', max_length=255, null=True, verbose_name='phone_4')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='Страна')),
                ('ct', models.CharField(default='null', max_length=255, null=True, verbose_name='Город')),
                ('st', models.CharField(default='null', max_length=255, null=True, verbose_name='Область')),
                ('zipzip', models.CharField(default='null', max_length=255, null=True, verbose_name='Индекс')),
                ('madid', models.CharField(default='null', max_length=255, null=True, verbose_name='madid')),
                ('uid', models.IntegerField(default=0, null=True, verbose_name='Facebook ID')),
                ('value', models.IntegerField(default=0, null=True, verbose_name='Сумма покупки')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='published')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Клиент дизайн студии',
                'verbose_name_plural': 'Заказчики ',
            },
        ),
        migrations.CreateModel(
            name='Private_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(default='null', max_length=255, null=True, verbose_name='ФИО')),
                ('mail', models.EmailField(default='null', max_length=254, null=True, verbose_name='email')),
                ('passportnumber', models.CharField(default='null', max_length=255, null=True, verbose_name='Паспорт')),
                ('issued', models.CharField(default='null', max_length=255, null=True, verbose_name='Кем выдан')),
                ('whenissued', models.DateField(default='null', null=True, verbose_name='Когда выдан')),
                ('placeofregistration', models.CharField(default='null', max_length=255, null=True, verbose_name='Место регистрации')),
                ('telephonenum', models.CharField(default='null', max_length=255, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Заказчик физлицо',
                'verbose_name_plural': 'Физ.лица ',
            },
        ),
    ]
