# Generated by Django 4.2.4 on 2024-02-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lids',
            fields=[
                ('name', models.CharField(default='unknown', max_length=100, null=True, verbose_name='name')),
                ('email', models.EmailField(default='unknown', max_length=254, null=True, verbose_name='email')),
                ('town', models.CharField(default='unknown', max_length=100, null=True, verbose_name='town')),
                ('telephone', models.CharField(default='unknown', max_length=20, null=True, verbose_name='phone')),
                ('area', models.IntegerField(default=0, null=True, verbose_name='area')),
                ('description', models.TextField(default='unknown', null=True, verbose_name='description')),
                ('source', models.TextField(null=True, verbose_name='source')),
                ('what_service', models.CharField(default='unknown', max_length=100, null=True, verbose_name='service')),
                ('our_price', models.IntegerField(default=0, null=True, verbose_name='price')),
                ('new', models.IntegerField(default=0, null=True, verbose_name='is new?')),
                ('date_now', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='date')),
                ('result', models.TextField(default='no result', null=True, verbose_name='result')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Лиды',
                'verbose_name_plural': 'Входящие заявки',
            },
        ),
    ]
