# Generated by Django 4.2.4 on 2024-03-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builders',
            fields=[
                ('ct', models.CharField(default='null', max_length=255, null=True, verbose_name='town')),
                ('fn', models.CharField(default='null', max_length=255, null=True, verbose_name='familia')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('ln', models.CharField(default='null', max_length=255, null=True, verbose_name='last_name')),
                ('specialisation', models.CharField(default='null', max_length=255, null=True, verbose_name='specialisation')),
                ('phone', models.CharField(null=True, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email_0')),
                ('site', models.URLField(null=True, verbose_name='site')),
                ('social_media', models.CharField(null=True, verbose_name='social medias')),
                ('organisation_name', models.CharField(default='null', max_length=255, null=True, verbose_name='organisation name')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='country')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='published')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=1, null=True, verbose_name='price per meter')),
                ('portfolio_image', models.ImageField(default='DEFAULT VALUE', null=True, upload_to='files/', verbose_name='example of work')),
                ('segment', models.CharField(default='econom', max_length=255, null=True, verbose_name='price segment')),
                ('legal_form', models.CharField(default='IP', max_length=255, null=True, verbose_name='legal form')),
                ('note', models.TextField(null=True, verbose_name='note')),
                ('make_an_estimate', models.BooleanField(default=False, verbose_name='make an estimate')),
                ('make_an_management', models.BooleanField(default=False, verbose_name='project management')),
                ('work_on_the_project', models.BooleanField(default=False, verbose_name='work on the project')),
                ('commission', models.BooleanField(default=False, verbose_name='give commissions')),
                ('organisation_structure', models.BooleanField(default=False, verbose_name='there is an organizational structure')),
                ('have_complectation', models.BooleanField(default=False, verbose_name='there is a supplier')),
                ('order', models.BooleanField(default=False, verbose_name='there is order at the working area')),
                ('universal', models.BooleanField(default=False, verbose_name='work with universal')),
                ('stock', models.BooleanField(default=False, verbose_name='there is a warehouse')),
                ('quality', models.BooleanField(default=False, verbose_name='internal quality control')),
                ('in_work', models.IntegerField(default=1, null=True, verbose_name='objects in operation')),
                ('working_time', models.IntegerField(default=1, null=True, verbose_name='experience')),
            ],
            options={
                'verbose_name': 'Builders organisation',
                'verbose_name_plural': 'builders',
            },
        ),
    ]
