INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Крицкий Алексей', 47);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Инна', 48);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('общий', 49);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Телелинский Дмитрий', 51);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Козловская Людмила', 52);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Подставкин Роман Владимирович', 53);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Петухова Екатерина Сергеевна', 54);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Мирошина Валерия Николаевна', 55);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Сафадие Абдуль Халим Атеф', 56);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Козловцева Людмила Алексеевна', 57);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Понамарева Анна Сергеевна', 58);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Литвинова Ольга Генадьевна', 59);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('не указан', 60);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Хубецов Заурбек', 61);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Леванян Марина', 62);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Трапездников Вячеслав', 63);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Луценко Наталия', 64);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('3д школа', 65);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Нягу Сергей', 66);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Московец Николайн Леонидович', 67);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Уртаева Зарина Руслановна', 68);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Дроздов Константин', 69);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Каратаева Елена', 70);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Марина Гуреева', 71);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Стасовский Олег', 72);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Мамаева Алана', 73);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Микро кредитная организация', 74);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('РФ', 75);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Орифлейм', 76);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Олеся', 77);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('КраснодарЮгСтрой', 78);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('ВРЕП2', 79);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('@oprime.krd', 80);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Татьяна Шотохина', 81);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Дмитрий Окунев', 82);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Завада Ольга Александровна', 83);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Ольга Голенко', 84);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Наталья Луценко', 85);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Чедыгов Аслан', 86);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Ульяна Николаева', 87);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Мусин', 89);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('"АКЦИОНЕРНОЕ ОБЩЕСТВО "БЕЙК ИНВЕСТ"', 90);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Зубер Виталий Игоревич', 91);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Александр Айсуваков', 92);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Карпачев Андрей ООО Агро-Трейд', 93);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Литвинова Ольга', 94);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Марина Гумирова', 95);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('52', 96);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Елена Каратаева', 97);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('68', 98);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('ООО "Регион-Инвест"', 99);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('87', 100);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Олеся Испания', 101);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Тимошенко Инна', 102);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('6', 103);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('310', 104);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Королина Касаткина', 105);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('41', 106);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('272', 107);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Студия 23', 108);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('291', 109);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('110', 110);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('288', 111);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('107', 112);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('Мирошина', 113);
INSERT INTO "addprofit_customer_category" ("name", "id") VALUES ('317', 114);
