INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('Кристина', 'post@unknown.ru', 'Москва', '+79167141231', 500, 'Заказ из Инстаграм на полный дизайн проект с авторским надзором и комплектацией зх этажный дом в Южном Бутова. Адрес: м Букинская Аллея
Площадь: 500 кв.м. Стоимость Дизайн проект составляет: 1 750 000 рублей из расчета 3500 рублей за кв.м Стоимость замеров 45 000 рублей Итого:  1 795 000  рублей
Срок выполнения работ 80  рабочих дней. Сейчас заказчики живут за границей. Вернуться весной.', 'Instagram', NULL, 1795000, 1, '2024-02-02 00:00:00+00', 'no result', 7);
INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('Оксана', 'unknown@mail.ru', 'Краснодар', '+79064024857', 6, 'Заявка из Инстаграм. Дизайн ванной 6 м.кв.', 'Instagram', NULL, NULL, NULL, '2024-02-02 00:00:00+00', 'no result', 9);
INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('Телелинский Дмитрий', 'unknown@mail.ru', 'Краснодар', 'unknown', NULL, 'Нужно сделать перепланировку офиса на Думенко', 'постоянный клиент', NULL, NULL, NULL, '2024-02-02 00:00:00+00', 'Заказ отвалился из-за саботажа работницы снабжения. Пришлось вернуть 15000', 11);
INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('Телелинский Дмитрий', 'unknown@mail.ru', 'Омск', 'unknown', NULL, 'Нужно назначить отделку стен на производстве', 'постоянный клиент', NULL, 50000, NULL, '2024-02-02 00:00:00+00', 'В работе', 10);
INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('Алексей Кольцов', 'unknown@mail.ru', 'Краснодар', 'unknown', 30, 'Заявка из Тенчата. Требуется разработать дизайн гостиной совмещенной с кухней су и прихожую
https://tenchat.ru/2393080', 'Ten Chat', NULL, NULL, 1, '2024-02-02 00:00:00+00', 'Из-за того, что не смогли порекомендовать строителей, заказ отвалился', 8);
INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('Литвинова Ольга Генадьевна', 'unknown@mail.ru', 'Горловка', 'unknown', 0, 'Входная группа в Горловке', 'Повторное обращение', 'unknown', 15000, 0, '2024-02-26 10:49:29+00', 'Получили аванс', 2);
INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('Emry Setinkaya', 'unknown@mail.ru', 'Минск', '+905537161622', 70, 'Заявка с сайта. Дизайн квартиры', 'Сайт', 'unknown', 5000, 1, '2024-02-22 10:52:01+00', 'Отправили КП', 3);
INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('Маргарита', 'unknown@mail.ru', 'Краснодар', 'unknown', 100, 'Заявка на замеры Маргарита', 'whatsaap. Заявка с сайта', 'unknown', 0, 0, '2024-02-21 10:55:11+00', 'Делаем замеры', 4);
INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('Маргарита', 'unknown@mail.ru', 'Краснодар', '+79963812152', 270, 'Заявка на замеры коммерческого помещения в Краснодаре 270 м.кв.', 'Сайт', 'unknown', 25000, 0, '2024-02-02 11:04:35+00', 'no result', 6);
INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('не указан', 'no@no.ru', 'Краснодар', 'no', 22, 'Заявка дизайн магазина армянских продуктов 22 мкв Индустриальный в ТЦ Любимово', 'сайт', 'unknown', 0, 0, '2024-02-12 10:59:52+00', 'no result', 5);
INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('Daniil', 'no@no.ru', 'Краснодар', '79615171658', 2, 'Добрый вечер. Извините  что поздно. Увидел объявление, что осуществляете замеры. Подскажите, осуществляете ли такую услугу и какая цена?', 'WhatsApp', 'unknown', 0, 0, '2024-02-13 11:18:41+00', 'no result', 12);
INSERT INTO "lids_lids" ("name", "email", "town", "telephone", "area", "description", "source", "what_service", "our_price", "new", "date_now", "result", "id") VALUES ('Московец Николайн Леонидович', 'unknown@mail.ru', 'Станица Азовская', '+79180438355', 100, 'Полный дизайн проект со схематичной визуализацией.Начать с замров и планировки', 'Постоянный клиент', 'Полный проект', 2000, 0, '2024-02-14 10:46:10+00', 'Работаем', 1);
