# Generated by Django 4.2.4 on 2024-02-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('key', models.CharField(db_index=True, max_length=50, verbose_name='key')),
                ('value', models.CharField(db_index=True, max_length=50, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Настройки telegram бота',
                'verbose_name_plural': 'Константы ',
            },
        ),
    ]
