# Generated by Django 4.2.4 on 2023-12-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addprofit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Заказчик')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_delegate', models.CharField(default='Иванов Иван Иванович', max_length=255, null=True, verbose_name='ФИО представителя')),
                ('mail', models.EmailField(default='neoluxe@yandex.ru', max_length=254, null=True, verbose_name='email')),
                ('telephonenum', models.CharField(default='+79780740854', max_length=25, null=True, verbose_name='телефон')),
                ('organization_full_name', models.CharField(default="Общество с ограниченной ответственностью 'Рога и копыта'", max_length=100, null=True, verbose_name='Полное наименование')),
                ('organization_adress', models.CharField(default="Общество с ограниченной ответственностью 'Рога и копыта'", max_length=250, null=True, verbose_name='Адрес организации')),
                ('organization_inn', models.BigIntegerField(default=6658215373, null=True, verbose_name='ИНН')),
                ('organization_kpp', models.BigIntegerField(default=23100100, null=True, verbose_name='КПП')),
                ('ogrn', models.BigIntegerField(default=1026605606620, null=True, verbose_name='КПП')),
                ('okpo', models.CharField(default=8729037291, max_length=250, null=True, verbose_name='ОКПО')),
                ('organization_rs', models.CharField(default='12345678912345678912', max_length=250, null=True, verbose_name='Р/С')),
                ('bank_name', models.CharField(default='ПАО КБ УБРИР', max_length=25, null=True, verbose_name='Название банка')),
                ('bank_bik', models.CharField(default='046577795', max_length=25, null=True, verbose_name='БИК')),
                ('bank_ks', models.CharField(default='30101810900000000795', max_length=250, null=True, verbose_name='К/С')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrivateContract',
            fields=[
                ('private_contract_file', models.FileField(default='DEFAULT VALUE', null=True, upload_to='files/', verbose_name='Путь к файлу (Договор)')),
                ('quantity', models.IntegerField(default=0, null=True, verbose_name='Количество')),
                ('source', models.CharField(default='дизайн проект', max_length=300, null=True, verbose_name='Предмет договора')),
                ('price', models.IntegerField(default=0, null=True, verbose_name='Цена')),
                ('square', models.IntegerField(default=0, null=True, verbose_name='Площадь')),
                ('address_of_object', models.CharField(default='null', null=True, verbose_name='Адрес объекта')),
                ('town_object', models.CharField(default='null', null=True, verbose_name='Город')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('published', models.DateField(db_index=True, null=True, verbose_name='Дата')),
                ('customername', models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.PROTECT, to='addprofit.customer_category', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Договор физ.лицо',
                'verbose_name_plural': 'Договора с физ.лицами ',
            },
        ),
        migrations.CreateModel(
            name='ContractBase',
            fields=[
                ('contract_file', models.FileField(default='DEFAULT VALUE', null=True, upload_to='files/', verbose_name='Путь к файлу')),
                ('customer_delegate', models.CharField(default='Иванов Иван Иванович', max_length=255, null=True, verbose_name='ФИО представителя')),
                ('quantity', models.IntegerField(default=50, null=True, verbose_name='Количество')),
                ('prefix', models.DateTimeField(db_index=True, null=True, verbose_name='prefix')),
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер договора')),
                ('price', models.FloatField(default=100, null=True, verbose_name='цена')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='date')),
                ('mail', models.EmailField(default='neoluxe@yandex.ru', max_length=254, null=True, verbose_name='email')),
                ('total_cost', models.FloatField(default=10000, null=True, verbose_name='цена')),
                ('adressofobject', models.CharField(default='350010,г. Краснодар, ул. Зиповская, д. 5 Литера Х, офис 28', max_length=255, null=True, verbose_name='Адрес объекта')),
                ('townobject', models.CharField(default='Москва', max_length=255, null=True, verbose_name='Город')),
                ('telephonenum', models.CharField(default='+79780740854', max_length=15, null=True, verbose_name='телефон')),
                ('customer_firm', models.CharField(default="ООО 'Рога и копыта' ", max_length=50, null=True, verbose_name='Название организации')),
                ('organization_full_name', models.CharField(default="Общество с ограниченной ответственностью 'Рога и копыта'", max_length=100, null=True, verbose_name='Полное наименование')),
                ('organization_adress', models.CharField(default='г. Краснодарпу', max_length=250, null=True, verbose_name='Адрес организации')),
                ('customer_legal_basis', models.CharField(default='Устава предприятия', max_length=250, null=True, verbose_name='Основание')),
                ('organization_inn', models.BigIntegerField(default=6658215373, null=True, verbose_name='ИНН')),
                ('organization_kpp', models.BigIntegerField(default=23100100, null=True, verbose_name='КПП')),
                ('ogrn', models.BigIntegerField(default=1026605606620, null=True, verbose_name='КПП')),
                ('date_of_firm_registration', models.DateTimeField(null=True, verbose_name='дата регистрации')),
                ('okpo', models.BigIntegerField(default=8729037291, null=True, verbose_name='ОКПО')),
                ('organization_rs', models.CharField(default='12345678912345678912', max_length=250, null=True, verbose_name='Р/С')),
                ('bank_name', models.CharField(default='ПАО КБ УБРИР', max_length=15, null=True, verbose_name='Название банка')),
                ('bank_bik', models.CharField(default='046577795', max_length=15, null=True, verbose_name='БИК')),
                ('bank_ks', models.CharField(default='30101810900000000795', max_length=250, null=True, verbose_name='К/С')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='make_contract_base.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Договор с юр.лицом',
                'verbose_name_plural': 'Договора',
            },
        ),
    ]
