# Generated by Django 4.2.4 on 2024-02-19 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('make_contract_base', '__first__'),
        ('addprofit', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('town', models.CharField(max_length=255, verbose_name='Город')),
                ('offer_number', models.CharField(default='null', max_length=50, null=True, verbose_name='Номер КП')),
                ('value', models.IntegerField(default=0, null=True, verbose_name='Итоговая стоимость с учётом скидки')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата создания КП')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.IntegerField()),
                ('address', models.CharField(max_length=250, null=True, verbose_name='Адрес')),
                ('project_composition', models.CharField(choices=[('F', 'floor_plan'), ('DP', 'dimensional_plan'), ('M', 'measurements'), ('V', 'visualization')], default='F', max_length=2)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='addprofit.customer_category', verbose_name='Заказчик')),
                ('ruberic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='make_contract_base.contractbase', verbose_name='Номер договора')),
            ],
            options={
                'verbose_name': 'КП',
                'verbose_name_plural': 'Коммерческие предложения ',
            },
        ),
    ]
