# Generated by Django 4.2.4 on 2024-02-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='project_composition',
            field=models.CharField(choices=[('F', 'планировка'), ('DP', 'обмерный план'), ('M', 'обмеры'), ('V', 'визуализация'), ('FDP', 'полный дизайн проект'), ('FP', 'фор-проект'), ('CDP', 'проект с комплектацией'), ('ADP', 'проект с авторским надзором')], default='F', max_length=3),
        ),
    ]
