# Generated by Django 4.2.4 on 2024-02-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_offer', '0002_alter_offer_project_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_file',
            field=models.FileField(default='DEFAULT VALUE', null=True, upload_to='files/', verbose_name='Путь к файлу (КП)'),
        ),
    ]
