# Generated by Django 4.2.4 on 2024-02-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('make_contract_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Название проекта')),
                ('area', models.IntegerField()),
                ('address', models.CharField(max_length=250, null=True, verbose_name='Адрес')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('published', models.DateTimeField(db_index=True, null=True, verbose_name='Дата')),
                ('ruberic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='make_contract_base.contractbase', verbose_name='Номер договора')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Дизайн проект',
            },
        ),
    ]
